apiVersion: v1
kind: Service
metadata:
  name: feedback-app-api-service
spec:
  selector:
    app: feedback-app
  ports:
  - port: 3000
    targetPort: 3000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-app-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feedback-app
  template:
    metadata:
      labels:
        app: feedback-app
        environment: test
    spec:
      containers:
      - name: feedback-app-backend-api
        image: galaataman/feedback-app:v4.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: DB_USER
          value: postgres
        - name: DB_HOST
          value: feedback-app-database-service
        - name: DB_NAME
          value: feedbackdb
        - name: DB_PASSWORD
          value: password
        - name: DB_PORT
          value: "5432"
