apiVersion: v1
kind: Service
metadata:
  name: feedback-app-database-service
spec:
  selector:
    app: feedback-app-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-app-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedback-app-db
  template:
    metadata:
      labels:
        app: feedback-app-db
        environment: test
    spec:
      containers:
      - name: feedback-postgres-db
        image: postgres:16.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: feedbackdb
        livenessProbe:
          exec:
            command:
            - "pg_isready"
            - "-U"
            - "postgres"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 5
          successThreshold: 1
        volumeMounts:
        - name: feedback-database-volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: feedback-database-volume
        persistentVolumeClaim:
          claimName: feedback-database-pvc
